### PR TITLE
fix: updated validator query to fetch total list of validators

### LINKED ISSUE #44: Failed to find validator by commit validator address desmosvalcons....
## Bug description

Juno fails to store the block signatures and throws this error when the validator set size is larger than 100 
`re-enqueueing failed block err="failed to find validator by commit validator address desmosvalcons1wdw3n55z0ztfer2yw6rjtnyme7h54yu6qe75m7" `

### PR DESCRIPTION
**Pull request by MonikaCat**
## Description

Fixes #44

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.  
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: node/remote/node.go [hunk 1]
```diff
@@ -111,20 +111,23 @@ func (cp *Node) Validators(height int64) (*tmctypes.ResultValidators, error) {
...
+			}
+			vals.Validators = append(vals.Validators, result.Validators...)
+			vals.Count += result.Count
+			vals.Total = result.Total
+			currentPage += 1
 		}
-		vals.Validators = append(vals.Validators, result.Validators...)
-		vals.Count += result.Count
-		vals.Total = result.Total
+		stop = vals.Count == vals.Total
```
Comment (huichiaotsou) [inline node/remote/node.go]: I think we can omit the maxPages variable so if there're > 200 validators it'll still be able to handle it: 
```go
	currentPage := 1
	perPage := 100 // maximum 100 entries per page
	stop := false
	for !stop {
		result, err := cp.client.Validators(cp.ctx, &height, &currentPage, &perPage)
		if err != nil {
			return nil, err
		}

		vals.Validators = append(vals.Validators, result.Validators...)
		vals.Count += result.Count
		vals.Total = result.Total

		currentPage += 1
		stop = vals.Count == vals.Total
	}
```

Comment (rmontagnin) [reply node/remote/node.go]: Agree with @huichiaotsou, it's better to be more generic and allow `n` pages of validators, not only 2 cause we might exceed even 200 in the future

**Review by rmontagnin — APPROVED** [review]
LGTM
