### PR TITLE
fix: listen to new blocks using gRPC instead of websocket

### LINKED ISSUE #46: Juno keeps missing blocks without logging and enqueuing again
We keep experiencing miss blocks and those blocks were not logged and enqueued again meaning that those blocks were not in the queue from the beginning.

As new blocks are all enqueued to the worker's queue by[ listening `NewBlock` event](https://github.com/forbole/juno/blob/4f6319e432a544b0866cf62daae4ff2ff6cc9a8e/node/remote/node.go#L195), it is suspected that blocks will be not enqueued correctly if the node is not responding properly and the `Tendermint` event is not broadcasted correctly. 

Can this be refactored so that `JUNO` optimistically enqueues all blocks not exist in the database? For example, if the largest block height in the database is `H`, and the latest block height on chain is `H+10`,  it enqueues `H+1` to `H+10` in the queue without listening to the websocket event?

### PR DESCRIPTION
**Pull request by huichiaotsou**
## Description

closes #46

## Checklist
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.  
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: cmd/parse/parse.go [hunk 1]
```diff
@@ -153,25 +152,35 @@ func enqueueMissingBlocks(exportQueue types.HeightQueue, ctx *Context) {
...
 
-// startNewBlockListener subscribes to new block events via the Tendermint RPCConfig
-// and enqueues each new block height onto the provided queue. It blocks as new
-// blocks are incoming.
-func startNewBlockListener(exportQueue types.HeightQueue, ctx *Context) {
-	eventCh, cancel, err := ctx.Node.SubscribeNewBlocks("juno-new-blocks-listener")
-	defer cancel()
-
+// enqueueNewBlocks enqueues new block heights onto the provided queue.
+func enqueueNewBlocks(exportQueue types.HeightQueue, ctx *Context) {
```
Comment (rmontagnin) [inline cmd/parse/parse.go:156]: I think this function can be simplified as follows: 
```go
// enqueueNewBlocks enqueues new block heights onto the provided queue.
func enqueueNewBlocks(exportQueue types.HeightQueue, ctx *Context) {
	currHeight, err := ctx.Node.LatestHeight()
	if err != nil {
		panic(fmt.Errorf("failed to get last block from RPCConfig client: %s", err))
	}
	
	for {
		// Get the latest block height
		latestBlockHeight, err := ctx.Node.LatestHeight()
		if err != nil {
			panic(fmt.Errorf("failed to get last block from RPCConfig client: %s", err))
		}

		// Enqueue all heights from the current height up to the latest height
		for ; currHeight <= latestBlockHeight; currHeight++ {
			ctx.Logger.Debug("enqueueing new block", "height", currHeight)
			exportQueue <- currHeight
		}

		time.Sleep(config.Cfg.Parser.AvgBlockTime)
	}
}
```

What are your thoughts here?

Comment (huichiaotsou) [reply cmd/parse/parse.go:156]: HA thats true. let me push the update

**Review by rmontagnin — APPROVED** [review]

**Review by MonikaCat — APPROVED** [review]
